#creating a class for keeping trial information
class TrialStats:
    SCENARIO=""
    RELIABLE="N\A"
    BLUE_FLAG_GRABS=0
    BLUE_FLAG_SCORES=0
    RED_FLAG_GRABS=0
    RED_FLAG_SCORES=0
    TIMES_TAGGED=0
    SPEECH_COMMANDED=0
    DIALOG_ERROR=0
    COMMAND_CANCELED=0
    TIME_FROM_AQUATICUS_GAME_START=0.0

